### ISSUE TITLE
tweepy-self

### ISSUE THREAD

**Issue by alenkimov** [FatBeeBHW/twitter-aio-tool#1]
How about using my tweepy-self library?
https://github.com/alenkimov/tweepy-self

**Comment by FatBeeBHW** [comment]
@alenkimov give me one good reason to use it?

Also, twitter is so str8 forward that actually doing LIB for it is more pain than anything.
Also you have over done it, and you have a lot of uneeded stuff.

But overall, kudos. It does look good.
